version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js...
      - curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -  # Sets up Node.js 18 repository
      - sudo apt-get install -y nodejs  # Installs Node.js and npm
      - echo Installing project dependencies...
      - npm install
      - echo Installing Nginx...
      - sudo apt-get update -y
      - sudo apt-get install -y nginx

  pre_build:
    commands:
      - echo Running tests...
      - if [ -f ./node_modules/.bin/jest ]; then npm run test; else echo "Skipping tests, Jest not found."; fi  # Run tests if Jest is available

  build:
    commands:
      - echo Building the project...
      - npm run build  # Build static files

  post_build:
    commands:
      - echo Copying files to Nginx HTML directory...
      - sudo rm -rf /var/www/html/*
      - sudo cp -r dist/* /var/www/html/
      - echo Starting Nginx...
      - sudo nginx -s quit || true  # Stop any running Nginx instance
      - sudo nginx  # Start Nginx

artifacts:
  files:
    - '**/*'
  base-directory: dist  # Parcel output directory, adjust if necessary

cache:
  paths:
    - 'node_modules/**/*'
